import type { Metadata } from "next";
import { Inter, Gelasio } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const gelasio = Gelasio({ subsets: ["latin"], variable: "--font-gelasio", });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${gelasio.variable}`}>{children}</body>
    </html>
  );
}
